/*
 *EDGAR JACOB MORENO
  PROYECTO PROGAMACION INTERMEDIA MANEJO DE ARCHIVOS JAVA
CARNE :0117660514
 */
package CapaUsuario;

import CapaDatos.ArchivoAnuncios;
import CapaDatos.ArchivoClientes;
import CapaDatos.ArregloAnuncio;
import CapaDatos.ArregloClientes;
import CapaDatos.DatosAnuncios;
import CapaDatos.DatosCliente;
import CapaDatos.LectorAnuncio;
import CapaDatos.LectorCliente;
import javax.swing.JOptionPane;

/**
 *
 * @author edgar
 */
public class VentanaRAnuncios extends javax.swing.JFrame {

    /**
     * Creates new form VentanaRAnuncios
     */
    TipoAnuncio ventanaBuscar = new TipoAnuncio();
    public String dato = "";
    public String buscado = "";
    public boolean flag = false;
    public ArregloClientes vecCliente = new ArregloClientes();
    private DatosCliente cliente = new DatosCliente();
    ArchivoClientes archCliente = new ArchivoClientes();

    public ArregloAnuncio vecAnuncio = new ArregloAnuncio();
    private DatosAnuncios anuncio = new DatosAnuncios();
    ArchivoAnuncios archAnuncio = new ArchivoAnuncios();

    public LectorCliente lectorCliente = new LectorCliente();
    public LectorAnuncio lectorAnuncio = new LectorAnuncio();

    public VentanaRAnuncios() {
        vecCliente.getVector().clear();
        vecAnuncio.getAnContratados().clear();

        try {
            lectorCliente.abrirArchCliente();
            lectorCliente.leerArchClientes(vecCliente.getVector());
            lectorCliente.cerrar();
        } catch (Exception ex) {

        }

        try {
            lectorAnuncio.abrirArchAnuncio();
            lectorAnuncio.leerArchAnuncios(vecAnuncio.getAnContratados());
            lectorAnuncio.cerrar();
        } catch (Exception e) {

        }

        vecAnuncio.printOnSystem();
        vecCliente.printOnSystem();
        initComponents();

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton3.setText("Mostrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Buscar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(63, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)))
                .addGap(51, 51, 51))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jButton4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton3)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                .addGap(34, 34, 34))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 610, 320));

        jButton1.setText("REGRESAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 550, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaUsuario/Fondo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        DatosCliente aux = new DatosCliente();
        DatosAnuncios aAux = new DatosAnuncios();

        int reply = JOptionPane.showConfirmDialog(null, "TIENE EL ID DEL CLIENTE QUE COMPRO EL ANUNCIO ?", "BUSQUEDA ANUNCIOS", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            try {
                int id = Integer.parseInt(JOptionPane.showInputDialog("DIGITE EL ID "));

                if (!vecCliente.eval(id)) {
                    throw new Exception("VALOR NO ENCONTRADO");

                } else {
                    dato = vecAnuncio.Buscar(id);
                    aux = vecCliente.buscarCliente(id);
                    jTextArea1.setText("CLIENTE > |NOMBRE :" + aux.getNom() + "   APELIDOS :" + aux.getApe_1() + " " + aux.getApe_2() + "|\n" + dato);

                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);

            }

        } else {
            try {

                ventanaBuscar.setVisible(true);

                flag = true;

            } catch (Exception e) {

            }

            // aux = vecCliente.buscarCliente(id);
        }

// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //resetea vectores 
        vecCliente.getVector().clear();
        vecAnuncio.getAnContratados().clear();

        try {
            lectorCliente.abrirArchCliente();
            lectorCliente.leerArchClientes(vecCliente.getVector());
            lectorCliente.cerrar();
        } catch (Exception ex) {

        }

        try {
            lectorAnuncio.abrirArchAnuncio();
            lectorAnuncio.leerArchAnuncios(vecAnuncio.getAnContratados());
            lectorAnuncio.cerrar();
        } catch (Exception e) {

        }

        if (flag) {
            buscado = ventanaBuscar.tipo;
            dato = vecAnuncio.Buscar(buscado);

            jTextArea1.setText(dato);
        } else {

            jTextArea1.setText(vecAnuncio.getVectorValues());
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);            // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaRAnuncios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaRAnuncios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaRAnuncios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaRAnuncios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaRAnuncios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
