/*
 *EDGAR JACOB MORENO
  PROYECTO PROGAMACION INTERMEDIA MANEJO DE ARCHIVOS JAVA
CARNE :0117660514
 */
package CapaUsuario;

import CapaDatos.ArchivoAnuncios;
import CapaDatos.ArchivoClientes;
import CapaDatos.ArregloAnuncio;
import CapaDatos.ArregloClientes;
import CapaDatos.DatosAnuncios;
import CapaDatos.DatosCliente;
import CapaDatos.LectorAnuncio;
import CapaDatos.LectorCliente;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author edgar
 */
public class VentanaRClientes extends javax.swing.JFrame {

    int opcion = -1;

    public ArregloClientes vecCliente = new ArregloClientes();

    ArchivoClientes archCliente = new ArchivoClientes();

    public ArregloAnuncio vecAnuncio = new ArregloAnuncio();
    private DatosAnuncios anuncio = new DatosAnuncios();
    ArchivoAnuncios archAnuncio = new ArchivoAnuncios();

    public LectorCliente lectorCliente = new LectorCliente();
    public LectorAnuncio lectorAnuncio = new LectorAnuncio();

    /**
     * Creates new form VentanaRClientes
     */
    //SE CARGAN LOS DATOS DEL ARCHIVO AL PROGRAMA
    public VentanaRClientes() {
        //Se limpia el buffer
        vecCliente.getVector().clear();
        vecAnuncio.getAnContratados().clear();

        try {
            lectorCliente.abrirArchCliente();
            lectorCliente.leerArchClientes(vecCliente.getVector());
            lectorCliente.cerrar();
        } catch (Exception ex) {

        }

        try {
            lectorAnuncio.abrirArchAnuncio();
            lectorAnuncio.leerArchAnuncios(vecAnuncio.getAnContratados());
            lectorAnuncio.cerrar();
        } catch (Exception e) {

        }

        vecAnuncio.printOnSystem();
        vecCliente.printOnSystem();

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        bConfirma = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Actualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Borrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        bConfirma.setText("Confirmar ");
        bConfirma.setEnabled(false);
        bConfirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConfirmaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(104, 104, 104)
                        .addComponent(bConfirma))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(bConfirma))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 550, 290));

        jButton4.setText("REGRESAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 540, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CapaUsuario/Fondo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        opcion = 1;
        bConfirma.setEnabled(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bConfirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConfirmaActionPerformed
//SE LIMPIA EL BUFFER
        //Se limpia el buffer
        vecCliente.getVector().clear();
        vecAnuncio.getAnContratados().clear();

//SE LEEN LOS DATOS DEL ARCHIVO AL VECTOR
        try {
            lectorCliente.abrirArchCliente();
            lectorCliente.leerArchClientes(vecCliente.getVector());
            lectorCliente.cerrar();
        } catch (Exception ex) {

        }

        try {
            lectorAnuncio.abrirArchAnuncio();
            lectorAnuncio.leerArchAnuncios(vecAnuncio.getAnContratados());
            lectorAnuncio.cerrar();
        } catch (Exception e) {

        }

        try {
            switch (opcion) {
                case 1:

                    try {
                        //Se agregar un registro

                        DatosCliente cliente = new DatosCliente();

                        vecCliente.agregar(cliente);

                        // una vez agregado al vector se imprime en el archivo 
                        archCliente.abrirArchivo();
                        archCliente.imprime(vecCliente.getVector());
                        archCliente.cerrarArchivo();

                        // TODO add your handling code here:
                    } catch (Exception ex) {
                        Logger.getLogger(VentanaRClientes.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    break;

                case 2:
                    //se actualiza un registro 
                    vecCliente.actualizar();

                    archCliente.abrirArchivo();
                    archCliente.imprime(vecCliente.getVector());
                    archCliente.cerrarArchivo();

                    break;

                case 3: //BORRAR

                    try {
                        int id = Integer.parseInt(JOptionPane.showInputDialog("PORFAVOR DIGITE EL ID DEL REGISTRO A ELIMINAR"));
                        vecCliente.eliminar(id, vecAnuncio);

                        archCliente.abrirArchivo();
                        archCliente.imprime(vecCliente.getVector());
                        archCliente.cerrarArchivo();

                        break;
                    } catch (Exception e) {

                    }

                    //resetea vectores 
                    //SE LIMPIA EL BUFFER YA QUE LOS OBJETOS FUERON SERIALIZADOS 
                    vecCliente.getVector().clear();
                    vecAnuncio.getAnContratados().clear();

            }
        } catch (Exception e) {

        }


    }//GEN-LAST:event_bConfirmaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        opcion = 2;
        bConfirma.setEnabled(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        opcion = 3;
        bConfirma.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaRClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaRClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaRClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaRClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaRClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bConfirma;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
